- hosts: web
  tasks:
    - name: enable docker
      command: systemctl enable docker

    - name: start docker
      command: systemctl start docker

    - name: status docker
      command: systemctl status docker

    - name: download docker-compose
      command: curl -O -L https://dl.bintray.com/docker-compose/master/docker-compose-Linux-x86_64

    - name: Installs docker-compose
      command: mv docker-compose-Linux-x86_64 /usr/local/bin/docker-compose

    - name: chmod 755 docker-compose
      command: chmod 755 /usr/local/bin/docker-compose

    - name: mkdir /opt/mysql
      command: mkdir /opt/mysql
